FROM node:lts-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN echo "REACT_APP_API_URL=http://api.infocare.test" > .env.production.local
RUN npm run build

FROM nginx:latest as final
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 8080/tcp
CMD ["/usr/sbin/nginx", "-g", "daemon off;"]